@startuml "DispatchServlet Workflow"

start
:Request come in;
:Get WebApplicationContext
and Bound to request;
:Bound resolvers to request,
include locale, theme, multipart, ...;
:Get HandlerExecutionChain to handle request
in execution chain
(preprocessors, postprocessors, and controllers);
:Render view if model return;


@enduml