@startuml

interface Authentication {
    Collection<? extends GrantedAuthority> getAuthorities();
}

interface GrantedAuthority {
    + String getAuthority();
}

note left
GrantedAuthority
一般用于Role级别的粗力度权限, 即应用级的权限,
不用于资源实例的权限
end note

Authentication "1" *-- "*" GrantedAuthority

interface UserDetailsService

UserDetailsService -right-> GrantedAuthority: generate

interface ConfigAttribute

interface AccessDecisionManager {
    void decide(Authentication authentication, Object secureObject, Collection<ConfigAttribute> attrs) throws AccessDeniedException;
    boolean supports(ConfigAttribute attribute);
    boolean supports(Class clazz);
}

AccessDecisionManager --> ConfigAttribute

abstract class AbstractAccessDecisionManager

AccessDecisionManager <|.. AbstractAccessDecisionManager

interface AccessDecisionVoter {
    int vote(Authentication authentication, Object object, Collection<ConfigAttribute> attrs);
    boolean supports(ConfigAttribute attribute);
    boolean supports(Class clazz);
}

AbstractAccessDecisionManager "1" *-right- "*" AccessDecisionVoter

AbstractAccessDecisionManager <|-- AffirmativeBased: 1+ access will grant

AccessDecisionVoter <|.. RoleVoter

GrantedAuthority <|.. SimpleGrantedAuthority

abstract class AbstractSecurityInterceptor

AbstractSecurityInterceptor "1" o-- "1" AccessDecisionManager: pre-invocation handling

interface AfterInvocationManager

AbstractSecurityInterceptor "1" o-- "1" AfterInvocationManager: after-invocation handling

AfterInvocationManager <|.. AfterInvocationProviderManager

AfterInvocationProviderManager "1" *-- "*" AfterInvocationProvider

@enduml